#!/bin/sh

ln -sf "$PWD/scripts/auto-rebuild" .git/hooks/post-merge && chmod +x .git/hooks/post-merge
echo "yarn check:yarnlock && yarn check:lint && yarn format && yarn check:regen-fixtures" > .git/hooks/pre-commit && chmod +x .git/hooks/pre-commit
echo "yarn build && yarn test:unit" > .git/hooks/pre-push && chmod +x .git/hooks/pre-push
