name: ci
on:
  push:
    branches: '*'
  pull_request:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [12]
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
          - node: 10
            os: ubuntu-latest
          - node: 14
            os: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: yarn --frozen-lockfile
      - run: yarn build
      - run: yarn test:unit
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: yarn --frozen-lockfile
      - run: yarn check:lint
  wintest:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: git config --global user.email "electrodenative@gmail.com"
      - run: git config --global user.name "Electrode Native"
      - uses: actions/setup-node@v1
      - run: yarn --frozen-lockfile
      - run: yarn test:system misc
  linuxtest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git config --global user.email "electrodenative@gmail.com"
      - run: git config --global user.name "Electrode Native"
      - uses: actions/setup-node@v1
      - run: yarn --frozen-lockfile
      - run: yarn test:system misc
